version: "3.8"

services:
  web:
    build: .
    image: web
  gateway:
    build: ./gateway
    image: gateway
    ports:
      - "80:80"
      - "443:443"
      - "25565:25565"
    volumes:
      - letsencrypt:/etc/letsencrypt
      - gateway_log:/var/log/nginx
      - web_log:/tobari/logs

volumes:
  letsencrypt:
    external: true
  gateway_log:
    driver: local
  web_log:
    driver: local